### ISSUE TITLE
Clicking on idle-user tab shows Application error

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-status#384]
![image](https://user-images.githubusercontent.com/42349041/211180169-0ebcc464-e482-41d1-8cae-8f1b109f0aec.png)

Steps to reproduce:
Currently, unable to reproduce

**Comment by RitikJaiswal75** [comment]
I Looked into the preview builds even they were failing.

its something over from vercel.

**Comment by Maheima** [comment]
https://discussions.apple.com/thread/253645567#:~:text=The%20message%20%22Application%20error%3A%20a,the%20standards%20your%20browser%20expects.

**Comment by Maheima** [comment]
When I checked the builds weren't failing which is why I merged it

**Comment by RitikJaiswal75** [comment]
Console is alerting on some map being used

**Comment by RitikJaiswal75** [comment]
Could we rollback the deploy @Maheima

**Comment by RitikJaiswal75** [comment]
While the deploy is rolled back we have an application working for everyone and we can look at the issue in the staging after that.

**Comment by yesyash** [comment]
## Issue
The problem seems to be in `src/pages/ideal-users.tsx` of #382 as pointed out by @sakshambhatt. 
Where when there is an error the `response` value in `line number 13` is set to an empty object ({}).

This results in the condition inside useEffect being truthy, and as there is no `allUserStatus` key in this empty object `idealUsersList` is set to `undefined`, mapping over undefined it is not possible it throws us an error on the client. 

Typescript does help us prevent the race condition for undefined because the `response`  returned from `useFetch` function is of type any. 

![image](https://user-images.githubusercontent.com/56453897/211233085-67c999d1-8967-4049-a2df-8309f498248d.png)

## Proposed solution
### Quick fix
A quick fix to this issue can be to replace the before code with after:

<table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td> 

```typescript
  const {
    response,
    error,
    isLoading,
  } = useFetch(IDLE_USERS_URL);

  useEffect(() => {
    if (response) {
      const idleUsers = response.allUserStatus;
      setIdleUsersList(idleUsers);
    }
  }, [isLoading, response]);
```
</td>

<td>
  
```typescript
const [idleUsersList, setIdleUsersList] = useState<IdleUser[]>([]);

  const {
    response,
    error,
    isLoading,
  } = useFetch(IDLE_USERS_URL);

  useEffect(() => {
    if (response && response.allUserStatus) {
      const idleUsers = response.allUserStatus;
      setIdleUsersList(idleUsers);
    }
  }, [isLoading, response]);
```
</td>
</tr>
</table>


### A Better Solution
Make `useFetch`  a generic function and make the its consumer explicitly mention response type.
